# Generated by Django 4.2.7 on 2025-11-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='image',
            field=models.ImageField(blank=True, help_text='Company logo or experience image', null=True, upload_to='experiences/'),
        ),
    ]
