# Generated by Django manually

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_experience_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='live_url',
        ),
    ]
