# Generated by Django manually

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_project_live_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Project screenshot or banner', null=True, upload_to='projects/'),
        ),
    ]
