# Generated by Django manually

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('LANG', 'Languages'), ('FRAME', 'Frameworks'), ('AIML', 'AI/ML'), ('BACK', 'Backend/Databases'), ('CLOUD', 'Cloud/DevOps'), ('TOOL', 'Developer Tools'), ('FUND', 'CS Fundamentals'), ('OTHER', 'Other')], default='OTHER', max_length=5),
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', 'display_order', 'name']},
        ),
    ]
