# Generated by Django 4.2.7 on 2026-02-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_add_skill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Order for display within category'),
        ),
    ]
